### ISSUE TITLE
Issue with titlebar buttons on windows

### ISSUE THREAD

**Issue by CleverCarpet** [KorbsStudio/electron-titlebar-os-detection#3]
When trying to use the buttons I get the error "Uncaught TypeError: Cannot read properties of undefined (reading 'send')"

I have only tested this on windows and cannot find a solution

**Comment by KorbsStudio** [comment]
Are you using IPCMain and IPCRenderer?

**Comment by CleverCarpet** [comment]
I figured the problem, I was using a previous custom method and then for got to set context isolation back to true
